spring:
  application:
    name: rodalivre-backend

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:rodalivre_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console

  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: ${JPA_FORMAT_SQL:false}
    show-sql: ${JPA_SHOW_SQL:false}

  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:4b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c}
  expiration: 900000 # 15 minutos em ms
  refresh-expiration: 604800000 # 7 dias em ms

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health
